version: '3'

services:
  web:
    image: haseebbhinder/tekron
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: tekron
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: